name: iv_project_widget_core
description: "A new Flutter package project."
version: 0.0.4
homepage:
publish_to: none

environment:
  sdk: ^3.10.8
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  iv_project_core:
    git:
      url: https://github.com/faequl96/iv_project_core.git
      ref: 0.1.2

  quick_dev_sdk:
    git:
      url: https://github.com/faequl96/quick_dev_sdk.git
      ref: 0.1.0+1

  bloc: ^9.2.0
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
