name: iv_project_widget_core
description: "A new Flutter package project."
version: 0.0.5
homepage:
publish_to: none

environment:
  sdk: ^3.10.8
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  iv_project_core:
    path: ../iv_project_core

  quick_dev_sdk:
    path: ../quick_dev_sdk

  bloc: ^9.2.0
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
